FROM nginx:latest


COPY ./index.html /usr/share/nginx/html

EXPOSE 80

# adicionar a uma rede propria antes da execução.
#utilize o comando docker builder prune -a (CUIDADO: ele removerá todos os cache do seu computador)
